CUDA_VISIBLE_DEVICES=0 uv run vllm serve pfnet/plamo-2-translate \
  --dtype bfloat16 \
  --kv-cache-dtype fp8 \
  --enable-prefix-caching \
  --gpu-memory-utilization 0.8 \
  --block-size 16 \
  --max-model-len 32768 \
  --max-num-seqs 512 \
  --max-num-batched-tokens 256k \
  --disable-log-requests \
  --host 0.0.0.0 --port 8000